### ISSUE TITLE
Laravel 10x illuminate/auth dependency conflict

### ISSUE THREAD

**Issue by elegisandi** [ForestAdmin/laravel-forestadmin#67]
## Expected behavior

Package installation won't be a problem.

## Actual behavior

Package installation failed when running `composer require forestadmin/laravel-forestadmin`.

## Failure Logs

    Problem 1
    - Root composer.json requires forestadmin/laravel-forestadmin * -> satisfiable by forestadmin/laravel-forestadmin[1.0.0, ..., 1.2.5].
    - forestadmin/laravel-forestadmin[1.0.0, ..., 1.2.5] require illuminate/auth ^8.0|^9.0 -> found illuminate/auth[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.

## Context

Running on my local machine using laravel-sail (docker)

* Package Version: latest
* Laravel Version: 10.3.1

**Comment by elegisandi** [comment]
@nicolasalexandre9 i see. thanks!

**Comment by nicolasalexandre9** [comment]
Hi @elegisandi,

We have just released the version 1.3, which is compatible with Laravel 10. 🎉
