### ISSUE TITLE
Laravel v11 compatibility? illuminate/auth & illuminate/cache dependency issues

### ISSUE THREAD

**Issue by mngarwood** [ForestAdmin/laravel-forestadmin#86]
## Expected behavior

Able to install the laravel-forestadmin package in my Laravel 11 project without issue.

## Actual behavior

Installation fails.

## Failure Logs

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - forestadmin/laravel-forestadmin[1.0.0, ..., 1.2.6] require illuminate/auth ^8.0|^9.0 -> found illuminate/auth[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - forestadmin/laravel-forestadmin[1.3.0, ..., 1.3.1] require illuminate/auth ^8.0|^9.0|^10.0 -> found illuminate/auth[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.18] but these were not loaded, likely because it conflicts with another require.
    - forestadmin/laravel-forestadmin[2.0.0, ..., 2.1.2, 3.0.0, ..., 3.0.2] require illuminate/cache ^8.0|^9.0|^10.0 -> found illuminate/cache[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.18] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires forestadmin/laravel-forestadmin * -> satisfiable by forestadmin/laravel-forestadmin[1.0.0, ..., 1.3.1, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 3.0.0, 3.0.1, 3.0.2].

## Context

M1 Mac, composer updated to latest stable version (2.7.7).

* Package Version: any (prefer latest)
* Laravel Version: v11.10.0

**Comment by matthv** [comment]
Hello @mngarwood 

Thanks for your feedback.
I have just created a ticket on our dashboard and will get back to you as soon as we have resolved the compatibility issue with laravel 11.

**Comment by mngarwood** [comment]
Thank you @matthv!

Do you have any rough guess as to how long it might be (days, weeks, or months)? That would help me make better informed decisions for my current project.

**Comment by matthv** [comment]
We have estimated it at about a week.
I'll keep you posted as soon as we publish.

**Comment by mngarwood** [comment]
Amazing! I was able to install without issue. Thanks so much, and thanks for the explanation.
